ebi-uniprot/QuickGoFE

app/styles/quickgo-colours.scss

This is a comment about the comment

Test commit

---

app/styles/quickgo-colours.scss
app/styles/quickgo.scss

Done the core SCSS conversion.  We can tweak some variable names after this is in, but this is ok for now I think. It's certainly a good starting point

New version of SCSS

---

app/advancedfilters/advancedFiltersModal.html
app/directives/megasearch.html
app/slimming/slimming.html
app/styles/quickgo.scss

A few layout tweaks, and improving the grammar and text clues.
Also replacing database centric instructions, to make them more user friendly.

advanced filters layout tidy up, and text improvements

---

app/index.html

Nothing more to say about this!

GOA-1666 Fix the logo jumping about between home page and others

---

app/term/term.html

GOA-1680 - removed unused table ID's

---

app/advancedfilters/advancedFilters.js
app/advancedfilters/advancedFiltersModal.html
app/scripts/services/filteringService.js
app/slimming/slimming.html
app/slimming/slimming.js

1st is some preliminary adding of slims to the advanced filters. This is not wired up yet, but the selector is added.
2nd  the wiring up of the gene product ID to slimming page

Two things here

---

app/slimming/slimming.js

Put an IF block around the function so its only fired if there is an input in the text area

Fixing bug that stopped slimming submit if no Gene Prod ID input

---

app/charts/ontologyGraph.js
app/charts/ontologyGraphModal.html
app/term/ancestorsGraph.js
app/term/term.html

ECO should be passed into as the scope if ECO (NOT GO which never needs to be passed in as its the default).

Fix eco charts. 

---

app/advancedfilters/advancedFilters.js
app/scripts/services/filteringService.js

Fixes https://www.ebi.ac.uk/panda/jira/browse/GOA-1926 and https://www.ebi.ac.uk/panda/jira/browse/GOA-1918

Added validation for taxonid, GO and ECO terms

---

app/term/term.html
app/term/term.js

The GOSlim sub section on the term page isn't showing the count of terms in that slim.

Fix goslim subcounts.

---

app/term/term.js

ECO term pages should not show Restrictions in the overview

---

app/annotationsList/annotationList.html
app/annotationsList/annotationList.js
app/scripts/services/wsService.js

So we correctly link to gene produc pages, and display gene product name, synonym and type

Use gene product service in annotations page.

---

app/annotationsList/annotationExtensionModal.html
app/annotationsList/annotationList.html
app/annotationsList/annotationList.js
app/annotationsList/withStringModal.html
app/scripts/app.js
app/scripts/filters.js
app/scripts/services/wsService.js
app/search/facetSearch.js
app/searchproducts/searchProducts.html
app/term/term.html

The taxonomy service is required in both annotations and gene product search results.

Use taxonomy service in annotations and gene product search results.

---

app/directives/facets.html
app/directives/facets.js
app/scripts/services/wsService.js
app/search/facetSearch.js
app/searchproducts/searchProducts.html

Add taxonomy facet and changes to new facet filter style on the back end (only available right now for gene product so filters will not work for terms).

Goa 2184 update facets geneprod

---

app/advancedfilters/evidenceFilter.js
app/advancedfilters/filterButtons.js
app/advancedfilters/geneProductFilter.js
app/advancedfilters/referencesFilter.js
app/advancedfilters/taxonFilter.js
app/advancedfilters/withFromFilter.js

There was a few which didn't:
- references
-with from
- ECOs

Goa 2484 Reference filter does not remember PMIDs

---

app/directives/coterms.html
app/directives/coterms.js
app/index.html
app/scripts/services/wsService.js
app/term/term.html
app/term/term.js

Slim, co-occurrences and protein complexes added. Change log updated.

Goa 2132 complete go term

---

app/download/download.html
app/download/downloadStatistics.html
app/download/downloadStatistics.js
app/index.html
app/statistics/statistics.html
app/statistics/statistics.js

Creates html and controller for downloading statistics and adds closing functionality to annotations download.

Goa 2360 download statistics

---

app/directives/coterms.html
app/directives/facets.html
app/directives/megasearch.html
app/searchproducts/searchProducts.html
app/searchterms/searchTerms.html
app/slimming/slimming.html

* It also updates a statistic field.

Add number filter to numbers.

---

app/advancedfilters/aspectFilter.html
app/advancedfilters/aspectFilter.js
app/advancedfilters/assignedByFilter.html
app/advancedfilters/assignedByFilter.js
app/advancedfilters/evidenceFilter.html
app/advancedfilters/evidenceFilter.js
app/advancedfilters/filterService.js
app/advancedfilters/geneProductFilter.html
app/advancedfilters/geneProductFilter.js
app/advancedfilters/goTermsFilter.html
app/advancedfilters/goTermsFilter.js
app/advancedfilters/productTypeFilter.html
app/advancedfilters/productTypeFilter.js
app/advancedfilters/qualifierFilter.html
app/advancedfilters/qualifierFilter.js
app/advancedfilters/referencesFilter.html
app/advancedfilters/referencesFilter.js
app/advancedfilters/taxonFilter.html
app/advancedfilters/taxonFilter.js
app/advancedfilters/withFromFilter.html
app/advancedfilters/withFromFilter.js
app/index.html
test/spec/controllers/taxon-filter-spec.js
test/spec/services/filterService-spec.js

In order to solve GOA-2512 (QuickGO filters input order) I decided it was a good occasion to simplify the filtering code by abstracting some of the commonly shared methods to Angular services.

Filtering service refactor

---

app/advancedfilters/filterService.js
app/advancedfilters/goTermsFilter.html
app/advancedfilters/goTermsFilter.js
app/scripts/services/hardcoded-data.js
app/slimming/slimming.html
app/slimming/slimming.js
app/styles/quickgo.scss

Root terms should be removed from predefined slim sets unless the checkbox is ticked. There was also quite a lot of obsolete bootstrap code which I've updated to foundation.

Goa 2369 add root terms

---

app/directives/megasearch.html
app/directives/megasearch.js

The code establishes if the user is on the homepage or not, and then applies a width to the mega search that matches that of the searchbox that currently visible to the client

GOA-2531 - resizing mega search drop down to match input box width

---

app/annotationsList/annotationList.html
app/directives/basket.js
app/download/download.html
app/download/download.js
app/download/downloadStatistics.html
app/scripts/services/hardcoded-data.js
app/scripts/services/wsService.js
app/statistics/statistics.html

* Styling changes: rename download to export, remove cancel button, rename Sumbit to Go
* Hides and removes html call for statistics download but keeps html and js in case we decide to activate it later
* Adds download service

Implement annotations download.

---

app/styles/quickgo.scss
app/term/term.html

Moved a couple of things around, and added a style class to control the icon size from within an H2 tag

GOA-2656 - changing the layout of the term page header area

---

app/download/download.html
app/faq/export_limit.html
app/faq/filter_limits.html
app/faq/gene_product_export.html
app/faq/human_proteome.html
app/help/doc.html
app/help/help.html
app/scripts/app.js

Simple FAQ updates and text changes

Goa 2711 faq new pages

---

app/advancedfilters/qualifierFilter.js
app/scripts/app.js
app/scripts/services/hardcoded-data.js
app/scripts/services/wsService.js
test/spec/controllers/qualifier-spec.js

Anything coming from presets has now been removed from hard coded service

Goa 2626 clean hardcodedservice

---

app/advancedfilters/advancedFilters.js
app/advancedfilters/annotationExtensionFilter.js
app/advancedfilters/aspectFilter.js
app/advancedfilters/assignedByFilter.js
app/advancedfilters/evidenceFilter.js
app/advancedfilters/geneProductFilter.js
app/advancedfilters/goTermsFilter.js
app/advancedfilters/morePanel.js
app/advancedfilters/productTypeFilter.js
app/advancedfilters/qualifierFilter.js
app/advancedfilters/referencesFilter.js
app/advancedfilters/taxonFilter.js
app/advancedfilters/withFromFilter.js
app/directives/addFading.js
app/index.html
app/scripts/app.js
app/slimming/slimming.js
app/styles/quickgo.scss

The directive is used as part of the ng-repeat so a timeout is created per alert/warning. When closed or cleared, the timeout is cleared out.

Add directive to fade out alerts/warnings.

---

app/searchproducts/searchProducts.html
app/searchterms/searchTerms.html

Two additional instances of the nav blocking removed

Removing two instances of nav blocking

---

app/searchproducts/searchProducts.html
app/searchterms/searchTerms.html

The class fixes the issue about not moving to the next page when clicking 2 in pagination bar

Add class to pagination directive.

---

app/advancedfilters/referencesFilter.js
app/scripts/services/wsService.js
app/statistics/statistics.html
app/statistics/statistics.js
test/spec/controllers/limitChecker.js

Implement functionality for the statistics download.
Some information is still missing on the file, but that is on the back end part. We just take the file and save it.

Goa 2988 add export stats button

---

.vscode/settings.json
app/statistics/statistics.html
app/statistics/statistics.js

Adding a tab to show slimming stats if slimming has been applied.

Goa 3069 slimming stats

---

app/statistics/statistics.html
app/statistics/statistics.js

I kept the word "distinct", otherwise I followed the requirements on the corresponding jira issue.

Use all or about depending conditions

---

app/advancedfilters/geneProductFilter.js
app/annotationsList/annotationList.html
app/annotationsList/annotationList.js

Taxon id and taxon name are shown together and interacting taxon can be added via customized columns

Goa 3071 interacting taxon

---

app/directives/chart.html
app/directives/chart.js

Here is the link to the ticket:
https://www.ebi.ac.uk/panda/jira/browse/GOA-3503
There are a few Angular related issues here that aren't addressed yet in this PR. We may or may not want to address them as they are all minor.
1. I wasn't able to normally update the `scope` when a selection was made in the dropdown list, but managed to find a way to pass it to the function that I needed via function arguments. You can see the code here:
https://github.com/ebi-uniprot/QuickGoFE/blob/chart-options-input-field/app/directives/chart.html#L19
2. I also wasn't able to have a default selection using `ng-init` for the list, therefore, nothing is selected by default and there seem to be an empty `option` added to the list too:
https://github.com/ebi-uniprot/QuickGoFE/blob/chart-options-input-field/app …

with dropdown list to multiply chart size
